#!/bin/bash
set -ex

# kamal proxy コンテナの起動オプションを設定
# - ホストの rsyslog にログを出力
# - ログのフォーマットを RFC5424 にする
# - userns=host でホストのユーザ名前空間を利用

if [ -z "$KAMAL_DESTINATION" ]; then
  kamal proxy boot_config set \
    --docker_options \
      log-driver=syslog \
      log-opt=syslog-address=udp://127.0.0.1:514 \
      log-opt=syslog-facility=daemon \
      log-opt=tag=proxy \
      log-opt=syslog-format=rfc5424 \
      userns=host
else
  kamal proxy -d "$KAMAL_DESTINATION" boot_config set \
    --docker_options \
      log-driver=syslog \
      log-opt=syslog-address=udp://127.0.0.1:514 \
      log-opt=syslog-facility=daemon \
      log-opt=tag=proxy \
      log-opt=syslog-format=rfc5424 \
      userns=host
fi
