FROM ruby:3.3.6

ENV LANG=C.UTF-8

RUN apt-get update -qq \
  && apt-get install --no-install-recommends -y \
  autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libcurl4-openssl-dev libxml2-dev \
  default-mysql-client \
  nodejs npm vim \
  povray povray-includes \
  libvips \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /src
WORKDIR /src

ENV GEM_VERSION=3.6.2
RUN gem update --system $GEM_VERSION
RUN gem install foreman

# Use OpenSSL 1.x
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm install -g npm-check-updates

RUN useradd -m --shell /bin/bash --uid 1000 ruby
USER ruby

ENV EDITOR=vim
ENV BUNDLE_PATH=vendor/bundle

RUN bundle config --global retry 5 \
  && bundle config --global path $BUNDLE_PATH

ENV BINDING=0.0.0.0
ENTRYPOINT [ "/src/docker/docker-entrypoint.sh" ]
