FROM ruby:2.6.6

ENV LANG=C.UTF-8

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update -qq \
  && apt-get install --no-install-recommends -y \
  autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libcurl4-openssl-dev libxml2-dev \
  default-mysql-client \
  nodejs vim \
  povray povray-includes \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /src
WORKDIR /src

ENV GEM_VERSION=3.4.21
RUN gem update --system $GEM_VERSION
ENV BUNDLER_VERSION=2.4.22
RUN gem install bundler -v $BUNDLER_VERSION

RUN useradd -m --shell /bin/bash --uid 1000 ruby
USER ruby

ENV EDITOR=vim
ENV BUNDLE_PATH=vendor/bundle

RUN bundle config --global retry 5 \
  && bundle config --global path $BUNDLE_PATH

ENTRYPOINT [ "/src/docker/docker-entrypoint.sh" ]
