development: &default
  secret_key_base: "8fa5ee056fe9918a5aff8e7ec3b301"
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>

test:
  <<: *default

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>

staging:
  <<: *default
