production:
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'mysql2' } %>
  encoding: utf8mb4
  database: gitfab2_production
  pool: <%= ENV.fetch('DB_POOL') { 5 } %>
  username: <%= ENV.fetch('DB_USER') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
